# Generated by Django 4.2.3 on 2023-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=120, verbose_name='Название')),
                ('email', models.CharField(max_length=100, verbose_name='Эл. почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефон')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(verbose_name='Дата создание')),
            ],
        ),
    ]
